"""add dialogues table

Revision ID: 5454bd7ffe20
Revises: 329e2ec555c7
Create Date: 2026-09-01 18:19:26.020042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5454bd7ffe20'
down_revision: Union[str, Sequence[str], None] = '329e2ec555c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('lead_type', sa.Enum('HOT', 'COLD', name='dialogueleadtype'), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'ERROR', name='dialoguestatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_dialogues_project_id'), 'dialogues', ['project_id'], unique=False)
    op.create_index(op.f('ix_dialogues_uploaded_by'), 'dialogues', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialogues_uploaded_by'), table_name='dialogues')
    op.drop_index(op.f('ix_dialogues_project_id'), table_name='dialogues')
    op.drop_table('dialogues')
    # ### end Alembic commands ###
